# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.16
      uses: actions/setup-node@v2
      with:
        node-version: 14.16.0
    - name: Install Dependencies
      working-directory: ./src/main/resources/static/js
      run: npm ci
    - name: Run Frontend Tests
      working-directory: ./src/main/resources/static/js
      run: npm test
